### ISSUE TITLE
Error using plugin

### ISSUE THREAD

**Issue by tyler36** [rpkoller/ddev-spidergram#1]
Thank you for making the addon.

When I attempted to try it on a existing project, I get the following error:

```shell
failed to solve: process "/bin/sh -c npx playwright install-deps" did not complete successfully: exit code: 1 
Failed to restart loaner-d10-demo: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-loaner-d10-demo docker-compose -f /home/user13/code/drupal/playground/loaner-d10-demo/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [ddev/ddev-webserver:20230509_gitpod_output-loaner-d10-demo-built internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s
....
#14 54.82 : Failed to fetch http://deb.debian.org/debian/pool/main/libo/libopenmpt/libopenmpt0_0.4.11-1_amd64.deb  Undetermined Error [IP: 151.101.230.132 80]
#14 54.82 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
#14 54.85 Failed to install browser dependencies
#14 54.85 Error: Installation process exited with code: 100
#14 ERROR: process "/bin/sh -c npx playwright install-deps" did not complete successfully: exit code: 1

**Comment by rpkoller** [comment]
hmmm that is odd. i am unable to reproduce. until you've opened the issue i've always tested on newly created empty projects. I never had any issue there installing. I've then went ahead and added the add-on for an already existing drupal project. but same there, i am able to install the add-on, restart the project, run through all the npm and npx commands without any issue and run spidergram commands in the end. 

your test project is running node 18? and have you installed other node dependencies in that project before you've added ddev-spidergram? the latter might be the only difference i might think of compared to my testing environment? cuz error code 100 doesn't sound like a network issue or timeout or something like that?

**Comment by tyler36** [comment]
hmmm ... just tried it on a new Laravel project (originally was Drupal) and have the same error. 🤷

**Comment by tyler36** [comment]
OK ... now it seems to be working? 

Trying to debug it by disabling `docker-compose.arangodb.yaml` and it loaded fine. Then noticed you comment about installing node dependencies so ran `ddev npm install`. Everything worked. Re-enabled `docker-compose.arangodb.yaml` and DDEV loaded.

OK, let's reproduce it. Started a new project, added the addon and it worked. 
Went back to original Drupal project, reinstalled it, and it worked. 

So, not really sure what is going on. But I'm not able to replicate it now. 
Closing. Thanks for the followup.
